### ISSUE TITLE
Docker setup fails due to missing images

### ISSUE THREAD

**Issue by MidnightLightning** [blockstack/packaging#15]
The `launcher` script [currently looks for](https://github.com/blockstack/packaging/blob/master/browser-core-docker/launcher#L5) the `latest` and `latest-browser` tags in [the Quay registry](https://quay.io/repository/blockstack/blockstack-core?tab=tags), which fails because while there is a `latest` tag, there is not a `latest-browser`.

There's not even any pair of "core" and "-browser" tags in the registry currently that match, so even overriding that value with a static version number doesn't work.

**Comment by kantai** [comment]
The `latest` and `latest-browser` issue can be fixed pretty easily --

I'll push the quay builds from the latest correct tags.

I'm looking into the versioning quay tags issue now.

**Comment by kantai** [comment]
Okay -- the following tags are now correct for version v0.19.0:

```
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
quay.io/blockstack/blockstack-browser   latest              ad688f45fe04        2 hours ago         1.01 GB
quay.io/blockstack/blockstack-browser   v0.19.0             ad688f45fe04        2 hours ago         1.01 GB
```

```
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
quay.io/blockstack/blockstack-core   latest-browser      954f597f4f91        2 hours ago         518 MB
quay.io/blockstack/blockstack-core   v0.19.0-browser     954f597f4f91        2 hours ago         518 MB
```

**Comment by kantai** [comment]
I'm not seeing the issue with missing tags --

the two repositories seem to have matching tags to me (example is v0.17.1, but the latest version is v0.19.0)

```
 $ docker pull quay.io/blockstack/blockstack-core:v0.17.1-browser
 ...
Digest: sha256:3d8a6f77c39e78c0e7ea61b98594d018e0c2a4bad9657514c9ba880d8ff89c1e
```

```
 $ docker pull quay.io/blockstack/blockstack-browser:v0.17.1
 ...
Digest: sha256:43560f30e3d7b7c81c74f31e5651e6ea10fbce3f6c990f5fee9b9b80379af678
```


Getting the repository and tag right is important: the _core_ repository needs to use the `vX.Y.Z-browser` tag, which indicates that it is the version of _core_ which ships with `vX.Y.Z` of the browser, the _browser_ repository uses the plain `vX.Y.Z` tag.

**Comment by MidnightLightning** [comment]
Ah, yes you're right with the missing tags; I was missing the fact that it was separate registries!
